export const COMMON_CHANGE_THEME_MODE = 'COMMON_CHANGE_THEME_MODE';

export const LOCALIZATION_INIT_I18N = 'LOCALIZATION_INIT_I18N';
export const LOCALIZATION_CHANGE_LANGUAGE = 'LOCALIZATION_CHANGE_LANGUAGE';